/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four
million, find the sum of the even-valued terms.
*/

#include <stdio.h>

unsigned long solution_1(unsigned long);
unsigned long solution_2(unsigned long);

int main()
{
    unsigned long upper_limit = 4000000;
    unsigned long s1, s2;

    s1 = solution_1(upper_limit);
    s2 = solution_2(upper_limit);

    printf("s1: %d, s2: %d\n", s1, s2);
    return 0;
}